In [1]:
import numpy as np

In [6]:
dados_a = [2, 3, 4, 5, 6, 7, 8]
dados_b = [1, 11, 1, 11, 1, 11, 1]

dados_a_np = np.array(dados_a)
dados_b_np = np.array(dados_b)

print(type(dados_a))
print(type(dados_a_np))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
print(dados_a + dados_b)
print(dados_a_np + dados_b_np)
print(dados_a * 2)
print(dados_a_np * 2)

[2, 3, 4, 5, 6, 7, 8, 1, 11, 1, 11, 1, 11, 1]
[ 3 14  5 16  7 18  9]
[2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8]
[ 4  6  8 10 12 14 16]


<style>
    .md {
        font-family: Consolas, Monospace;
        font-size: 16px;
    }
    .br, .en {
        padding: 10px 0;
    }
    .en {
        border-top: 1px dotted lightgray;
        color: #444;
    }
</style>
<div class="md">
<div class="br">
Quando utilizamos algum operador lógico em um ndarray, o retorno é um ndarray de mesmas dimensões com True ou False para cada elemento testado. Isso pode ser utilizado como índice no mesmo ndarray ou outro de mesma dimensão para selecionar somente os rows que atendem a alguma especificação.
</div>
<div class="en">
When we utilize some logical operator over a ndarray, the return is an another ndarray with the same dimension fully of True or False to each element tested. This can be utilized as an index in the same ndarray or another of the same dimension to select the rows which match some specification.
</div>
</div>

In [14]:
print(dados_a_np > 4)
print(dados_a_np[dados_a_np > 4])

[False False False  True  True  True  True]
[5 6 7 8]


<style>
    .md {
        font-family: Consolas, Monospace;
        font-size: 16px;
    }
    .br, .en {
        padding: 10px 0;
    }
    .en {
        border-top: 1px dotted lightgray;
        color: #444;
    }
    h2 {
        font-size: 20px;
    }
</style>

<div class=md>
<div class=br>
<h2>Arrays multidimensionais</h2>
</div>
<div class=en>
<h2>Multidimensional arrays</h2>
</div>
</div>

In [19]:
multidimensional = np.array([
    ['name', 'Finn', 1],
    ['name', 'Jake', 2],
    ['name', 'Bubblegum', 3],
    ['name', 'Marceline', 4],
    ['name', 'Simon Petrikov', 5]]
)
print(multidimensional.shape)
print(multidimensional)

(5, 3)
[['name' 'Finn' '1']
 ['name' 'Jake' '2']
 ['name' 'Bubblegum' '3']
 ['name' 'Marceline' '4']
 ['name' 'Simon Petrikov' '5']]


<style>
    .md {
        font-family: Consolas, Monospace;
        font-size: 16px;
    }
    .br, .en {
        padding: 10px 0;
    }
    .en {
        border-top: 1px dotted lightgray;
        color: #444;
    }
</style>
<div class="md">
<div class="br">
Uma das características do ndarray é que ele pode conter apenas elementos com mesmo tipo. Perceba no exemplo anterior que havia números na matriz, porém, após a criação do ndarray, os números foram convertidos para string. Isso sempre acontecerá.
</div>
<div class="en">
One ndarray characteristic is that it can contain only elements of the same type. Notice in the previous example there were numbers in matrix, but, after the ndarray creation, the numbers were converted into strings. That will always happen. 
</div>
</div>